-- CreateEnum
CREATE TYPE "SocialPlatform" AS ENUM ('YOUTUBE', 'INSTAGRAM', 'GITHUB', 'FACEBOOK', 'TWITTER');

-- CreateEnum
CREATE TYPE "Role" AS ENUM ('USER', 'EDITOR', 'CONTRIBUTER', 'SPONSOR', 'ADMIN', 'OWNER');

-- CreateEnum
CREATE TYPE "Like" AS ENUM ('LIKED', 'DISLIKED', 'NONE');

-- CreateEnum
CREATE TYPE "Status" AS ENUM ('PUBLISHED', 'DRAFT');

-- CreateTable
CREATE TABLE "User" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "blocked" BOOL NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL,
    "email" STRING NOT NULL,
    "email_verified" BOOL NOT NULL,
    "family_name" STRING NOT NULL,
    "given_name" STRING NOT NULL,
    "last_ip" STRING NOT NULL,
    "last_login" TIMESTAMP(3) NOT NULL,
    "logins_count" INT4 NOT NULL,
    "name" STRING NOT NULL,
    "nickname" STRING NOT NULL,
    "phone_number" STRING NOT NULL,
    "phone_verified" BOOL NOT NULL DEFAULT false,
    "picture" STRING NOT NULL,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "user_id" STRING NOT NULL,
    "username" STRING NOT NULL,
    "profileId" INT8 NOT NULL,
    "role" "Role" NOT NULL DEFAULT 'USER',

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Follows" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "followedById" INT8 NOT NULL,
    "followingId" INT8 NOT NULL,

    CONSTRAINT "Follows_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Post" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" STRING NOT NULL,
    "body" STRING NOT NULL,
    "slug" STRING NOT NULL,
    "description" STRING NOT NULL,
    "featuredImage" STRING NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "schema" JSONB NOT NULL,
    "status" "Status" NOT NULL DEFAULT 'PUBLISHED',
    "like" "Like" NOT NULL DEFAULT 'NONE',
    "taxonomyId" INT8 NOT NULL,
    "postsOnProfileId" INT8 NOT NULL,
    "postsByPublicationId" INT8,
    "contributedOnPostsByProfileId" INT8,
    "postsOnTaxonomyId" INT8,
    "postsOnBookmarkId" INT8,

    CONSTRAINT "Post_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Page" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" STRING NOT NULL,
    "body" STRING NOT NULL,
    "slug" STRING NOT NULL,
    "description" STRING NOT NULL,
    "featuredImage" STRING NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "schema" JSONB NOT NULL,
    "status" "Status" NOT NULL DEFAULT 'PUBLISHED',
    "like" "Like" NOT NULL DEFAULT 'NONE',
    "pagesOnProfileId" INT8 NOT NULL,
    "contributedOnPagesByProfileId" INT8,

    CONSTRAINT "Page_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Blog" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" STRING NOT NULL,
    "body" STRING NOT NULL,
    "slug" STRING NOT NULL,
    "description" STRING NOT NULL,
    "featuredImage" STRING NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "schema" JSONB NOT NULL,
    "status" "Status" NOT NULL DEFAULT 'PUBLISHED',
    "like" "Like" NOT NULL DEFAULT 'NONE',
    "blogsOnProfileId" INT8 NOT NULL,
    "contributedOnBlogsByProfileId" INT8,

    CONSTRAINT "Blog_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Taxonomy" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "category1Id" INT8 NOT NULL,
    "category2Id" INT8 NOT NULL,
    "taxonomiesCreatedByProfileId" INT8,

    CONSTRAINT "Taxonomy_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Category" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "slug" STRING NOT NULL,
    "description" STRING NOT NULL,
    "logo" STRING NOT NULL,

    CONSTRAINT "Category_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Profile" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "bio" STRING NOT NULL,
    "userId" INT8 NOT NULL,

    CONSTRAINT "Profile_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Publication" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "slug" STRING NOT NULL,
    "description" STRING NOT NULL,
    "logo" STRING NOT NULL,
    "rolesByPublicationId" INT8,
    "publicationsByProfileId" INT8,

    CONSTRAINT "Publication_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Header" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,

    CONSTRAINT "Header_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Footer" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,

    CONSTRAINT "Footer_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "HeaderItem" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "slug" STRING NOT NULL,
    "description" STRING,
    "itemsRelId" INT8 NOT NULL,
    "headerId" INT8,

    CONSTRAINT "HeaderItem_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "FooterItem" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "slug" STRING NOT NULL,
    "description" STRING,
    "itemsRelId" INT8 NOT NULL,
    "footerId" INT8,

    CONSTRAINT "FooterItem_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PostsByPublication" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "publicationId" INT8 NOT NULL,

    CONSTRAINT "PostsByPublication_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PublicationsByProfile" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "profileId" INT8 NOT NULL,

    CONSTRAINT "PublicationsByProfile_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RolesByPublication" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,

    CONSTRAINT "RolesByPublication_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RolesOnPublicationByProfile" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "profileId" INT8 NOT NULL,
    "publicationId" INT8 NOT NULL,
    "role" "Role" NOT NULL DEFAULT 'EDITOR',
    "rolesByPublicationId" INT8,

    CONSTRAINT "RolesOnPublicationByProfile_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PostsOnProfile" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "profileId" INT8 NOT NULL,

    CONSTRAINT "PostsOnProfile_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PagesOnProfile" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "profileId" INT8 NOT NULL,

    CONSTRAINT "PagesOnProfile_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "BlogsOnProfile" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "profileId" INT8 NOT NULL,

    CONSTRAINT "BlogsOnProfile_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ContributedOnPostsByProfile" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "profileId" INT8 NOT NULL,

    CONSTRAINT "ContributedOnPostsByProfile_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ContributedOnPagesByProfile" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "profileId" INT8 NOT NULL,

    CONSTRAINT "ContributedOnPagesByProfile_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ContributedOnBlogsByProfile" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "profileId" INT8 NOT NULL,

    CONSTRAINT "ContributedOnBlogsByProfile_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TagsOnPost" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "postId" INT8 NOT NULL,

    CONSTRAINT "TagsOnPost_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TagsOnPage" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "pageId" INT8 NOT NULL,

    CONSTRAINT "TagsOnPage_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TagsOnBlog" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "blogId" INT8 NOT NULL,

    CONSTRAINT "TagsOnBlog_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TagsCreatedByProfile" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "profileId" INT8 NOT NULL,

    CONSTRAINT "TagsCreatedByProfile_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TaxonomiesCreatedByProfile" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "profileId" INT8 NOT NULL,

    CONSTRAINT "TaxonomiesCreatedByProfile_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Tag" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "slug" STRING NOT NULL,
    "description" STRING NOT NULL,
    "logo" STRING NOT NULL,
    "tagsOnPostId" INT8,
    "tagsOnPageId" INT8,
    "tagsOnBlogId" INT8,
    "tagsCreatedByProfileId" INT8,

    CONSTRAINT "Tag_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "UserOnPost" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "userId" INT8 NOT NULL,
    "postId" INT8 NOT NULL,

    CONSTRAINT "UserOnPost_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "UserOnPage" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "userId" INT8 NOT NULL,
    "pageId" INT8 NOT NULL,

    CONSTRAINT "UserOnPage_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "UserOnBlog" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "userId" INT8 NOT NULL,
    "blogId" INT8 NOT NULL,

    CONSTRAINT "UserOnBlog_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Feedback" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "userId" INT8 NOT NULL,
    "feedback" STRING NOT NULL,
    "rating" INT4 NOT NULL,
    "postId" INT8,
    "pageId" INT8,
    "blogId" INT8,

    CONSTRAINT "Feedback_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CommentsOnPost" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "postId" INT8 NOT NULL,

    CONSTRAINT "CommentsOnPost_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CommentsOnBlog" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "blogId" INT8 NOT NULL,

    CONSTRAINT "CommentsOnBlog_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Comment" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "comment" STRING NOT NULL,
    "commentRelId" INT8 NOT NULL,
    "commentsOnPostId" INT8,
    "commentsOnBlogId" INT8,
    "userId" INT8 NOT NULL,

    CONSTRAINT "Comment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PostsOnTaxonomy" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "taxonomyId" INT8 NOT NULL,

    CONSTRAINT "PostsOnTaxonomy_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SocialAccountsOnProfile" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "profileId" INT8 NOT NULL,

    CONSTRAINT "SocialAccountsOnProfile_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SocialAccount" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "socialPlatform" "SocialPlatform" NOT NULL,
    "username" STRING NOT NULL,
    "socialAccountsOnProfileId" INT8,

    CONSTRAINT "SocialAccount_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Bookmark" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "userId" INT8 NOT NULL,
    "postsOnBookmarkId" INT8,

    CONSTRAINT "Bookmark_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PostsOnBookmark" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,

    CONSTRAINT "PostsOnBookmark_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- CreateIndex
CREATE UNIQUE INDEX "User_user_id_key" ON "User"("user_id");

-- CreateIndex
CREATE UNIQUE INDEX "User_username_key" ON "User"("username");

-- CreateIndex
CREATE UNIQUE INDEX "User_profileId_key" ON "User"("profileId");

-- CreateIndex
CREATE UNIQUE INDEX "Follows_followedById_followingId_key" ON "Follows"("followedById", "followingId");

-- CreateIndex
CREATE UNIQUE INDEX "Post_title_key" ON "Post"("title");

-- CreateIndex
CREATE UNIQUE INDEX "Post_body_key" ON "Post"("body");

-- CreateIndex
CREATE UNIQUE INDEX "Post_slug_key" ON "Post"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "Post_description_key" ON "Post"("description");

-- CreateIndex
CREATE UNIQUE INDEX "Post_featuredImage_key" ON "Post"("featuredImage");

-- CreateIndex
CREATE INDEX "Post_id_slug_idx" ON "Post"("id", "slug");

-- CreateIndex
CREATE UNIQUE INDEX "Page_title_key" ON "Page"("title");

-- CreateIndex
CREATE UNIQUE INDEX "Page_body_key" ON "Page"("body");

-- CreateIndex
CREATE UNIQUE INDEX "Page_slug_key" ON "Page"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "Page_description_key" ON "Page"("description");

-- CreateIndex
CREATE UNIQUE INDEX "Page_featuredImage_key" ON "Page"("featuredImage");

-- CreateIndex
CREATE INDEX "Page_id_slug_idx" ON "Page"("id", "slug");

-- CreateIndex
CREATE UNIQUE INDEX "Blog_title_key" ON "Blog"("title");

-- CreateIndex
CREATE UNIQUE INDEX "Blog_body_key" ON "Blog"("body");

-- CreateIndex
CREATE UNIQUE INDEX "Blog_slug_key" ON "Blog"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "Blog_description_key" ON "Blog"("description");

-- CreateIndex
CREATE UNIQUE INDEX "Blog_featuredImage_key" ON "Blog"("featuredImage");

-- CreateIndex
CREATE INDEX "Blog_id_slug_idx" ON "Blog"("id", "slug");

-- CreateIndex
CREATE UNIQUE INDEX "Taxonomy_category1Id_category2Id_key" ON "Taxonomy"("category1Id", "category2Id");

-- CreateIndex
CREATE UNIQUE INDEX "Category_name_key" ON "Category"("name");

-- CreateIndex
CREATE UNIQUE INDEX "Category_slug_key" ON "Category"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "Category_description_key" ON "Category"("description");

-- CreateIndex
CREATE UNIQUE INDEX "Category_logo_key" ON "Category"("logo");

-- CreateIndex
CREATE UNIQUE INDEX "Profile_bio_key" ON "Profile"("bio");

-- CreateIndex
CREATE UNIQUE INDEX "Profile_userId_key" ON "Profile"("userId");

-- CreateIndex
CREATE UNIQUE INDEX "Publication_name_key" ON "Publication"("name");

-- CreateIndex
CREATE UNIQUE INDEX "Publication_slug_key" ON "Publication"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "Publication_description_key" ON "Publication"("description");

-- CreateIndex
CREATE UNIQUE INDEX "Publication_logo_key" ON "Publication"("logo");

-- CreateIndex
CREATE UNIQUE INDEX "HeaderItem_name_key" ON "HeaderItem"("name");

-- CreateIndex
CREATE UNIQUE INDEX "HeaderItem_slug_key" ON "HeaderItem"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "HeaderItem_description_key" ON "HeaderItem"("description");

-- CreateIndex
CREATE UNIQUE INDEX "FooterItem_name_key" ON "FooterItem"("name");

-- CreateIndex
CREATE UNIQUE INDEX "FooterItem_slug_key" ON "FooterItem"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "FooterItem_description_key" ON "FooterItem"("description");

-- CreateIndex
CREATE UNIQUE INDEX "PostsByPublication_publicationId_key" ON "PostsByPublication"("publicationId");

-- CreateIndex
CREATE UNIQUE INDEX "PublicationsByProfile_profileId_key" ON "PublicationsByProfile"("profileId");

-- CreateIndex
CREATE UNIQUE INDEX "RolesOnPublicationByProfile_profileId_key" ON "RolesOnPublicationByProfile"("profileId");

-- CreateIndex
CREATE UNIQUE INDEX "RolesOnPublicationByProfile_publicationId_key" ON "RolesOnPublicationByProfile"("publicationId");

-- CreateIndex
CREATE UNIQUE INDEX "RolesOnPublicationByProfile_profileId_publicationId_key" ON "RolesOnPublicationByProfile"("profileId", "publicationId");

-- CreateIndex
CREATE UNIQUE INDEX "PostsOnProfile_profileId_key" ON "PostsOnProfile"("profileId");

-- CreateIndex
CREATE UNIQUE INDEX "PagesOnProfile_profileId_key" ON "PagesOnProfile"("profileId");

-- CreateIndex
CREATE UNIQUE INDEX "BlogsOnProfile_profileId_key" ON "BlogsOnProfile"("profileId");

-- CreateIndex
CREATE UNIQUE INDEX "ContributedOnPostsByProfile_profileId_key" ON "ContributedOnPostsByProfile"("profileId");

-- CreateIndex
CREATE UNIQUE INDEX "ContributedOnPagesByProfile_profileId_key" ON "ContributedOnPagesByProfile"("profileId");

-- CreateIndex
CREATE UNIQUE INDEX "ContributedOnBlogsByProfile_profileId_key" ON "ContributedOnBlogsByProfile"("profileId");

-- CreateIndex
CREATE UNIQUE INDEX "TagsOnPost_postId_key" ON "TagsOnPost"("postId");

-- CreateIndex
CREATE UNIQUE INDEX "TagsOnPage_pageId_key" ON "TagsOnPage"("pageId");

-- CreateIndex
CREATE UNIQUE INDEX "TagsOnBlog_blogId_key" ON "TagsOnBlog"("blogId");

-- CreateIndex
CREATE UNIQUE INDEX "TagsCreatedByProfile_profileId_key" ON "TagsCreatedByProfile"("profileId");

-- CreateIndex
CREATE UNIQUE INDEX "TaxonomiesCreatedByProfile_profileId_key" ON "TaxonomiesCreatedByProfile"("profileId");

-- CreateIndex
CREATE UNIQUE INDEX "Tag_slug_key" ON "Tag"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "Tag_description_key" ON "Tag"("description");

-- CreateIndex
CREATE UNIQUE INDEX "Tag_logo_key" ON "Tag"("logo");

-- CreateIndex
CREATE UNIQUE INDEX "UserOnPost_userId_key" ON "UserOnPost"("userId");

-- CreateIndex
CREATE UNIQUE INDEX "UserOnPage_userId_key" ON "UserOnPage"("userId");

-- CreateIndex
CREATE UNIQUE INDEX "UserOnBlog_userId_key" ON "UserOnBlog"("userId");

-- CreateIndex
CREATE UNIQUE INDEX "Feedback_userId_key" ON "Feedback"("userId");

-- CreateIndex
CREATE UNIQUE INDEX "CommentsOnPost_postId_key" ON "CommentsOnPost"("postId");

-- CreateIndex
CREATE UNIQUE INDEX "CommentsOnBlog_blogId_key" ON "CommentsOnBlog"("blogId");

-- CreateIndex
CREATE UNIQUE INDEX "Comment_commentRelId_key" ON "Comment"("commentRelId");

-- CreateIndex
CREATE UNIQUE INDEX "PostsOnTaxonomy_taxonomyId_key" ON "PostsOnTaxonomy"("taxonomyId");

-- CreateIndex
CREATE UNIQUE INDEX "SocialAccountsOnProfile_profileId_key" ON "SocialAccountsOnProfile"("profileId");

-- CreateIndex
CREATE UNIQUE INDEX "SocialAccount_socialPlatform_username_key" ON "SocialAccount"("socialPlatform", "username");

-- CreateIndex
CREATE UNIQUE INDEX "Bookmark_userId_key" ON "Bookmark"("userId");

-- CreateIndex
CREATE UNIQUE INDEX "Bookmark_postsOnBookmarkId_key" ON "Bookmark"("postsOnBookmarkId");

-- AddForeignKey
ALTER TABLE "User" ADD CONSTRAINT "User_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "Profile"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Follows" ADD CONSTRAINT "Follows_followedById_fkey" FOREIGN KEY ("followedById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Follows" ADD CONSTRAINT "Follows_followingId_fkey" FOREIGN KEY ("followingId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Post" ADD CONSTRAINT "Post_taxonomyId_fkey" FOREIGN KEY ("taxonomyId") REFERENCES "Taxonomy"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Post" ADD CONSTRAINT "Post_postsOnProfileId_fkey" FOREIGN KEY ("postsOnProfileId") REFERENCES "PostsOnProfile"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Post" ADD CONSTRAINT "Post_postsByPublicationId_fkey" FOREIGN KEY ("postsByPublicationId") REFERENCES "PostsByPublication"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Post" ADD CONSTRAINT "Post_contributedOnPostsByProfileId_fkey" FOREIGN KEY ("contributedOnPostsByProfileId") REFERENCES "ContributedOnPostsByProfile"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Post" ADD CONSTRAINT "Post_postsOnTaxonomyId_fkey" FOREIGN KEY ("postsOnTaxonomyId") REFERENCES "PostsOnTaxonomy"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Post" ADD CONSTRAINT "Post_postsOnBookmarkId_fkey" FOREIGN KEY ("postsOnBookmarkId") REFERENCES "PostsOnBookmark"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Page" ADD CONSTRAINT "Page_pagesOnProfileId_fkey" FOREIGN KEY ("pagesOnProfileId") REFERENCES "PagesOnProfile"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Page" ADD CONSTRAINT "Page_contributedOnPagesByProfileId_fkey" FOREIGN KEY ("contributedOnPagesByProfileId") REFERENCES "ContributedOnPagesByProfile"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Blog" ADD CONSTRAINT "Blog_blogsOnProfileId_fkey" FOREIGN KEY ("blogsOnProfileId") REFERENCES "BlogsOnProfile"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Blog" ADD CONSTRAINT "Blog_contributedOnBlogsByProfileId_fkey" FOREIGN KEY ("contributedOnBlogsByProfileId") REFERENCES "ContributedOnBlogsByProfile"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Taxonomy" ADD CONSTRAINT "Taxonomy_category1Id_fkey" FOREIGN KEY ("category1Id") REFERENCES "Category"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Taxonomy" ADD CONSTRAINT "Taxonomy_category2Id_fkey" FOREIGN KEY ("category2Id") REFERENCES "Category"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Taxonomy" ADD CONSTRAINT "Taxonomy_taxonomiesCreatedByProfileId_fkey" FOREIGN KEY ("taxonomiesCreatedByProfileId") REFERENCES "TaxonomiesCreatedByProfile"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Publication" ADD CONSTRAINT "Publication_rolesByPublicationId_fkey" FOREIGN KEY ("rolesByPublicationId") REFERENCES "RolesByPublication"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Publication" ADD CONSTRAINT "Publication_publicationsByProfileId_fkey" FOREIGN KEY ("publicationsByProfileId") REFERENCES "PublicationsByProfile"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "HeaderItem" ADD CONSTRAINT "HeaderItem_itemsRelId_fkey" FOREIGN KEY ("itemsRelId") REFERENCES "HeaderItem"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "HeaderItem" ADD CONSTRAINT "HeaderItem_headerId_fkey" FOREIGN KEY ("headerId") REFERENCES "Header"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FooterItem" ADD CONSTRAINT "FooterItem_itemsRelId_fkey" FOREIGN KEY ("itemsRelId") REFERENCES "FooterItem"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "FooterItem" ADD CONSTRAINT "FooterItem_footerId_fkey" FOREIGN KEY ("footerId") REFERENCES "Footer"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PostsByPublication" ADD CONSTRAINT "PostsByPublication_publicationId_fkey" FOREIGN KEY ("publicationId") REFERENCES "Publication"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PublicationsByProfile" ADD CONSTRAINT "PublicationsByProfile_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "Profile"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RolesOnPublicationByProfile" ADD CONSTRAINT "RolesOnPublicationByProfile_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "Profile"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RolesOnPublicationByProfile" ADD CONSTRAINT "RolesOnPublicationByProfile_publicationId_fkey" FOREIGN KEY ("publicationId") REFERENCES "Publication"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RolesOnPublicationByProfile" ADD CONSTRAINT "RolesOnPublicationByProfile_rolesByPublicationId_fkey" FOREIGN KEY ("rolesByPublicationId") REFERENCES "RolesByPublication"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PostsOnProfile" ADD CONSTRAINT "PostsOnProfile_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "Profile"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PagesOnProfile" ADD CONSTRAINT "PagesOnProfile_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "Profile"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BlogsOnProfile" ADD CONSTRAINT "BlogsOnProfile_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "Profile"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ContributedOnPostsByProfile" ADD CONSTRAINT "ContributedOnPostsByProfile_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "Profile"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ContributedOnPagesByProfile" ADD CONSTRAINT "ContributedOnPagesByProfile_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "Profile"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ContributedOnBlogsByProfile" ADD CONSTRAINT "ContributedOnBlogsByProfile_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "Profile"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TagsOnPost" ADD CONSTRAINT "TagsOnPost_postId_fkey" FOREIGN KEY ("postId") REFERENCES "Post"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TagsOnPage" ADD CONSTRAINT "TagsOnPage_pageId_fkey" FOREIGN KEY ("pageId") REFERENCES "Page"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TagsOnBlog" ADD CONSTRAINT "TagsOnBlog_blogId_fkey" FOREIGN KEY ("blogId") REFERENCES "Blog"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TagsCreatedByProfile" ADD CONSTRAINT "TagsCreatedByProfile_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "Profile"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TaxonomiesCreatedByProfile" ADD CONSTRAINT "TaxonomiesCreatedByProfile_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "Profile"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Tag" ADD CONSTRAINT "Tag_tagsOnPostId_fkey" FOREIGN KEY ("tagsOnPostId") REFERENCES "TagsOnPost"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Tag" ADD CONSTRAINT "Tag_tagsOnPageId_fkey" FOREIGN KEY ("tagsOnPageId") REFERENCES "TagsOnPage"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Tag" ADD CONSTRAINT "Tag_tagsOnBlogId_fkey" FOREIGN KEY ("tagsOnBlogId") REFERENCES "TagsOnBlog"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Tag" ADD CONSTRAINT "Tag_tagsCreatedByProfileId_fkey" FOREIGN KEY ("tagsCreatedByProfileId") REFERENCES "TagsCreatedByProfile"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UserOnPost" ADD CONSTRAINT "UserOnPost_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UserOnPost" ADD CONSTRAINT "UserOnPost_postId_fkey" FOREIGN KEY ("postId") REFERENCES "Post"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UserOnPage" ADD CONSTRAINT "UserOnPage_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UserOnPage" ADD CONSTRAINT "UserOnPage_pageId_fkey" FOREIGN KEY ("pageId") REFERENCES "Page"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UserOnBlog" ADD CONSTRAINT "UserOnBlog_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UserOnBlog" ADD CONSTRAINT "UserOnBlog_blogId_fkey" FOREIGN KEY ("blogId") REFERENCES "Blog"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Feedback" ADD CONSTRAINT "Feedback_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Feedback" ADD CONSTRAINT "Feedback_postId_fkey" FOREIGN KEY ("postId") REFERENCES "Post"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Feedback" ADD CONSTRAINT "Feedback_pageId_fkey" FOREIGN KEY ("pageId") REFERENCES "Page"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Feedback" ADD CONSTRAINT "Feedback_blogId_fkey" FOREIGN KEY ("blogId") REFERENCES "Blog"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CommentsOnPost" ADD CONSTRAINT "CommentsOnPost_postId_fkey" FOREIGN KEY ("postId") REFERENCES "Post"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CommentsOnBlog" ADD CONSTRAINT "CommentsOnBlog_blogId_fkey" FOREIGN KEY ("blogId") REFERENCES "Blog"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Comment" ADD CONSTRAINT "Comment_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Comment" ADD CONSTRAINT "Comment_commentRelId_fkey" FOREIGN KEY ("commentRelId") REFERENCES "Comment"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "Comment" ADD CONSTRAINT "Comment_commentsOnPostId_fkey" FOREIGN KEY ("commentsOnPostId") REFERENCES "CommentsOnPost"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Comment" ADD CONSTRAINT "Comment_commentsOnBlogId_fkey" FOREIGN KEY ("commentsOnBlogId") REFERENCES "CommentsOnBlog"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PostsOnTaxonomy" ADD CONSTRAINT "PostsOnTaxonomy_taxonomyId_fkey" FOREIGN KEY ("taxonomyId") REFERENCES "Taxonomy"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SocialAccountsOnProfile" ADD CONSTRAINT "SocialAccountsOnProfile_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "Profile"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SocialAccount" ADD CONSTRAINT "SocialAccount_socialAccountsOnProfileId_fkey" FOREIGN KEY ("socialAccountsOnProfileId") REFERENCES "SocialAccountsOnProfile"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Bookmark" ADD CONSTRAINT "Bookmark_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Bookmark" ADD CONSTRAINT "Bookmark_postsOnBookmarkId_fkey" FOREIGN KEY ("postsOnBookmarkId") REFERENCES "PostsOnBookmark"("id") ON DELETE SET NULL ON UPDATE CASCADE;
